import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { Image, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Svg, { Path } from 'react-native-svg';

import { LanguageSwitch } from '../../components/LanguageSwitch';
import { Button } from '../../components/ui';
import { COPY } from '../../copy';
import { useAppStore } from '../../state/AppStore';
import { color, font, fontFamily, radius, spacing, glass } from '../../theme';
import type { StepProps } from './types';

/**
 * The owner's own hero photograph (AI-generated by them, 2026-07-28): the
 * couple at the pool in the brand's dusk. It fades into the ground so the
 * wordmark stands on white, not on someone's shoulder.
 */
const HERO = require('../../../assets/welcome-hero.jpg');

const ShieldTile = () => (
  <View style={styles.shieldTile}>
    <Svg width={26} height={26} viewBox="0 0 24 24" fill={color.accentDeep} stroke={color.accentDeep} strokeWidth={1.5} strokeLinejoin="round">
      <Path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1 1 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
      <Path d="M8.5 11.8l2.6 2.6 4.8-4.8" stroke="#FFFFFF" strokeWidth={2.2} fill="none" strokeLinecap="round" />
    </Svg>
  </View>
);

const LockChip = () => (
  <View style={styles.lockChip}>
    <Svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke={color.accentDeep} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 11h14v10H5z" />
      <Path d="M8 11V7a4 4 0 0 1 8 0v4" />
    </Svg>
  </View>
);

/**
 * Phone OTP deliberately has no separate sign-up and sign-in journeys: the
 * same number/code exchange creates or restores the account without revealing
 * which one happened.
 */
export function WelcomeStep({ go }: StepProps) {
  const { dispatch } = useAppStore();
  const { width } = useWindowDimensions();

  // The wordmark is two-toned per the designer: the first word deep, the
  // second in the mid accent. Split from the one brand string so a rename
  // stays a one-line change.
  const [brandA, ...brandRest] = COPY.appName.split(' ');
  // The headline's full stop is a small heart in the reference.
  const headline = COPY.onboarding.welcome.headline.replace(/[.。]\s*$/, '');

  return (
    <SafeAreaView style={styles.screen} edges={['top', 'bottom']} testID="screen-welcome">
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.heroWrap}>
          <Image
            source={HERO}
            style={{ width, height: width * 0.82 }}
            resizeMode="cover"
            accessibilityIgnoresInvertColors
          />
          <LinearGradient
            colors={['transparent', color.background]}
            style={styles.heroFade}
            pointerEvents="none"
          />
          {/* The first decision on the first screen: which language the rest
              of this conversation happens in. Floats over the hero. */}
          <View style={styles.languageRow}>
            <LanguageSwitch testID="welcome-language" />
          </View>
        </View>

        <View style={styles.content}>
          <Text accessibilityRole="header" style={styles.wordmark}>
            <Text style={styles.wordmarkDeep}>{brandA}</Text>
            {brandRest.length > 0 ? <Text style={styles.wordmarkMid}>{` ${brandRest.join(' ')}`}</Text> : null}
          </Text>
          <Text accessibilityRole="header" style={styles.headline}>
            {headline}
            <Text style={styles.headlineHeart}> ♥</Text>
          </Text>
          <Text style={styles.body}>{COPY.onboarding.welcome.body}</Text>

          <View style={styles.trustCard}>
            <ShieldTile />
            <View style={styles.trustWords}>
              <Text style={styles.trustTitle}>{COPY.onboarding.welcome.trustTitle}</Text>
              <Text style={styles.trustBody}>{COPY.onboarding.welcome.trustBody}</Text>
            </View>
            <LockChip />
          </View>
        </View>

        <View style={styles.footer}>
          <Button
            label={COPY.onboarding.welcome.continueWithPhone}
            onPress={() => {
              dispatch({ type: 'CONFIRM_AGE' });
              go('promise');
            }}
            testID="welcome-phone"
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: color.background },
  scroll: { flexGrow: 1 },
  heroWrap: { position: 'relative' },
  languageRow: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.md,
  },
  content: { paddingHorizontal: spacing.md, alignItems: 'center', gap: spacing.sm },
  wordmark: {
    fontFamily: fontFamily.display,
    fontSize: font.title,
    letterSpacing: 0.4,
    textAlign: 'center',
  },
  wordmarkDeep: { color: color.accentDeep },
  wordmarkMid: { color: 'rgba(236, 72, 153, 0.55)' },
  headline: {
    fontFamily: fontFamily.display,
    fontSize: font.display,
    lineHeight: font.display * 1.15,
    color: color.ink,
    textAlign: 'center',
  },
  headlineHeart: { color: color.accentDeep, fontSize: font.heading },
  body: {
    fontFamily: fontFamily.body,
    fontSize: font.body,
    lineHeight: font.body * 1.5,
    color: color.inkMuted,
    textAlign: 'center',
    maxWidth: 320,
  },
  trustCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 4,
    alignSelf: 'stretch',
    backgroundColor: glass.fill,
    borderWidth: 1,
    borderColor: glass.edge,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginTop: spacing.sm,
    shadowColor: '#000000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  shieldTile: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: color.veil,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trustWords: { flex: 1, gap: 2 },
  trustTitle: {
    fontFamily: fontFamily.bodySemi,
    fontSize: font.body,
    color: color.ink,
  },
  trustBody: {
    fontFamily: fontFamily.body,
    fontSize: font.caption,
    lineHeight: font.caption * 1.45,
    color: color.inkMuted,
  },
  lockChip: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(236, 72, 153, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: { padding: spacing.md, gap: spacing.sm, marginTop: 'auto' },
  heroFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 110,
  },
});
