/**
 * Region names for both app languages, generated once from full-ICU Intl data.
 *
 * Why a table at all: Hermes — the engine Expo Go runs on a phone — does not
 * implement Intl.DisplayNames, so the runtime fallback in countries.ts showed
 * every country as its bare code ("TR / TR") on a real device while web and
 * jest, both on V8, looked fine. Names are UI reference data, not user data;
 * generating them once beats hand-maintaining 249 rows in two languages.
 *
 * Regenerate (from mobile/): the node heredoc in the repo history that wrote
 * this file — node reads its own ICU, so the output stays consistent.
 */
export const COUNTRY_NAMES: Record<'tr' | 'en', Record<string, string>> = {
  tr: {
    AD: 'Andorra',
    AE: 'Birleşik Arap Emirlikleri',
    AF: 'Afganistan',
    AG: 'Antigua ve Barbuda',
    AI: 'Anguilla',
    AL: 'Arnavutluk',
    AM: 'Ermenistan',
    AO: 'Angola',
    AQ: 'Antarktika',
    AR: 'Arjantin',
    AS: 'Amerikan Samoası',
    AT: 'Avusturya',
    AU: 'Avustralya',
    AW: 'Aruba',
    AX: 'Åland Adaları',
    AZ: 'Azerbaycan',
    BA: 'Bosna-Hersek',
    BB: 'Barbados',
    BD: 'Bangladeş',
    BE: 'Belçika',
    BF: 'Burkina Faso',
    BG: 'Bulgaristan',
    BH: 'Bahreyn',
    BI: 'Burundi',
    BJ: 'Benin',
    BL: 'Saint Barthelemy',
    BM: 'Bermuda',
    BN: 'Brunei',
    BO: 'Bolivya',
    BQ: 'Karayip Hollandası',
    BR: 'Brezilya',
    BS: 'Bahamalar',
    BT: 'Butan',
    BV: 'Bouvet Adası',
    BW: 'Botsvana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Kanada',
    CC: 'Cocos (Keeling) Adaları',
    CD: 'Kongo - Kinşasa',
    CF: 'Orta Afrika Cumhuriyeti',
    CG: 'Kongo - Brazavil',
    CH: 'İsviçre',
    CI: 'Côte d’Ivoire',
    CK: 'Cook Adaları',
    CL: 'Şili',
    CM: 'Kamerun',
    CN: 'Çin',
    CO: 'Kolombiya',
    CR: 'Kosta Rika',
    CU: 'Küba',
    CV: 'Cabo Verde',
    CW: 'Curaçao',
    CX: 'Christmas Adası',
    CY: 'Kıbrıs',
    CZ: 'Çekya',
    DE: 'Almanya',
    DJ: 'Cibuti',
    DK: 'Danimarka',
    DM: 'Dominika',
    DO: 'Dominik Cumhuriyeti',
    DZ: 'Cezayir',
    EC: 'Ekvador',
    EE: 'Estonya',
    EG: 'Mısır',
    EH: 'Batı Sahra',
    ER: 'Eritre',
    ES: 'İspanya',
    ET: 'Etiyopya',
    FI: 'Finlandiya',
    FJ: 'Fiji',
    FK: 'Falkland Adaları',
    FM: 'Mikronezya',
    FO: 'Faroe Adaları',
    FR: 'Fransa',
    GA: 'Gabon',
    GB: 'Birleşik Krallık',
    GD: 'Grenada',
    GE: 'Gürcistan',
    GF: 'Fransız Guyanası',
    GG: 'Guernsey',
    GH: 'Gana',
    GI: 'Cebelitarık',
    GL: 'Grönland',
    GM: 'Gambiya',
    GN: 'Gine',
    GP: 'Guadeloupe',
    GQ: 'Ekvator Ginesi',
    GR: 'Yunanistan',
    GS: 'Güney Georgia ve Güney Sandwich Adaları',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Gine-Bissau',
    GY: 'Guyana',
    HK: 'Çin Hong Kong ÖİB',
    HM: 'Heard Adası ve McDonald Adaları',
    HN: 'Honduras',
    HR: 'Hırvatistan',
    HT: 'Haiti',
    HU: 'Macaristan',
    ID: 'Endonezya',
    IE: 'İrlanda',
    IL: 'İsrail',
    IM: 'Man Adası',
    IN: 'Hindistan',
    IO: 'Britanya Hint Okyanusu Toprakları',
    IQ: 'Irak',
    IR: 'İran',
    IS: 'İzlanda',
    IT: 'İtalya',
    JE: 'Jersey',
    JM: 'Jamaika',
    JO: 'Ürdün',
    JP: 'Japonya',
    KE: 'Kenya',
    KG: 'Kırgızistan',
    KH: 'Kamboçya',
    KI: 'Kiribati',
    KM: 'Komorlar',
    KN: 'Saint Kitts ve Nevis',
    KP: 'Kuzey Kore',
    KR: 'Güney Kore',
    KW: 'Kuveyt',
    KY: 'Cayman Adaları',
    KZ: 'Kazakistan',
    LA: 'Laos',
    LB: 'Lübnan',
    LC: 'Saint Lucia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberya',
    LS: 'Lesotho',
    LT: 'Litvanya',
    LU: 'Lüksemburg',
    LV: 'Letonya',
    LY: 'Libya',
    MA: 'Fas',
    MC: 'Monako',
    MD: 'Moldova',
    ME: 'Karadağ',
    MF: 'Saint Martin',
    MG: 'Madagaskar',
    MH: 'Marshall Adaları',
    MK: 'Kuzey Makedonya',
    ML: 'Mali',
    MM: 'Myanmar (Burma)',
    MN: 'Moğolistan',
    MO: 'Çin Makao ÖİB',
    MP: 'Kuzey Mariana Adaları',
    MQ: 'Martinik',
    MR: 'Moritanya',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldivler',
    MW: 'Malavi',
    MX: 'Meksika',
    MY: 'Malezya',
    MZ: 'Mozambik',
    NA: 'Namibya',
    NC: 'Yeni Kaledonya',
    NE: 'Nijer',
    NF: 'Norfolk Adası',
    NG: 'Nijerya',
    NI: 'Nikaragua',
    NL: 'Hollanda',
    NO: 'Norveç',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Yeni Zelanda',
    OM: 'Umman',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'Fransız Polinezyası',
    PG: 'Papua Yeni Gine',
    PH: 'Filipinler',
    PK: 'Pakistan',
    PL: 'Polonya',
    PM: 'Saint Pierre ve Miquelon',
    PN: 'Pitcairn Adaları',
    PR: 'Porto Riko',
    PS: 'Filistin Bölgeleri',
    PT: 'Portekiz',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Katar',
    RE: 'Reunion',
    RO: 'Romanya',
    RS: 'Sırbistan',
    RU: 'Rusya',
    RW: 'Ruanda',
    SA: 'Suudi Arabistan',
    SB: 'Solomon Adaları',
    SC: 'Seyşeller',
    SD: 'Sudan',
    SE: 'İsveç',
    SG: 'Singapur',
    SH: 'Saint Helena',
    SI: 'Slovenya',
    SJ: 'Svalbard ve Jan Mayen',
    SK: 'Slovakya',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somali',
    SR: 'Surinam',
    SS: 'Güney Sudan',
    ST: 'Sao Tome ve Principe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Suriye',
    SZ: 'Esvatini',
    TC: 'Turks ve Caicos Adaları',
    TD: 'Çad',
    TF: 'Fransız Güney Toprakları',
    TG: 'Togo',
    TH: 'Tayland',
    TJ: 'Tacikistan',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Türkmenistan',
    TN: 'Tunus',
    TO: 'Tonga',
    TR: 'Türkiye',
    TT: 'Trinidad ve Tobago',
    TV: 'Tuvalu',
    TW: 'Tayvan',
    TZ: 'Tanzanya',
    UA: 'Ukrayna',
    UG: 'Uganda',
    UM: 'ABD Küçük Harici Adaları',
    US: 'Amerika Birleşik Devletleri',
    UY: 'Uruguay',
    UZ: 'Özbekistan',
    VA: 'Vatikan',
    VC: 'Saint Vincent ve Grenadinler',
    VE: 'Venezuela',
    VG: 'Britanya Virjin Adaları',
    VI: 'ABD Virjin Adaları',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis ve Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'Güney Afrika',
    ZM: 'Zambiya',
    ZW: 'Zimbabve',
  },
  en: {
    AD: 'Andorra',
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    AG: 'Antigua & Barbuda',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AS: 'American Samoa',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AX: 'Åland Islands',
    AZ: 'Azerbaijan',
    BA: 'Bosnia & Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BI: 'Burundi',
    BJ: 'Benin',
    BL: 'St. Barthélemy',
    BM: 'Bermuda',
    BN: 'Brunei',
    BO: 'Bolivia',
    BQ: 'Caribbean Netherlands',
    BR: 'Brazil',
    BS: 'Bahamas',
    BT: 'Bhutan',
    BV: 'Bouvet Island',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Cocos (Keeling) Islands',
    CD: 'Congo - Kinshasa',
    CF: 'Central African Republic',
    CG: 'Congo - Brazzaville',
    CH: 'Switzerland',
    CI: 'Côte d’Ivoire',
    CK: 'Cook Islands',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cape Verde',
    CW: 'Curaçao',
    CX: 'Christmas Island',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    EH: 'Western Sahara',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    FI: 'Finland',
    FJ: 'Fiji',
    FK: 'Falkland Islands',
    FM: 'Micronesia',
    FO: 'Faroe Islands',
    FR: 'France',
    GA: 'Gabon',
    GB: 'United Kingdom',
    GD: 'Grenada',
    GE: 'Georgia',
    GF: 'French Guiana',
    GG: 'Guernsey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Greenland',
    GM: 'Gambia',
    GN: 'Guinea',
    GP: 'Guadeloupe',
    GQ: 'Equatorial Guinea',
    GR: 'Greece',
    GS: 'South Georgia & South Sandwich Islands',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HK: 'Hong Kong SAR China',
    HM: 'Heard & McDonald Islands',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IM: 'Isle of Man',
    IN: 'India',
    IO: 'British Indian Ocean Territory',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KI: 'Kiribati',
    KM: 'Comoros',
    KN: 'St. Kitts & Nevis',
    KP: 'North Korea',
    KR: 'South Korea',
    KW: 'Kuwait',
    KY: 'Cayman Islands',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LC: 'St. Lucia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MC: 'Monaco',
    MD: 'Moldova',
    ME: 'Montenegro',
    MF: 'St. Martin',
    MG: 'Madagascar',
    MH: 'Marshall Islands',
    MK: 'North Macedonia',
    ML: 'Mali',
    MM: 'Myanmar (Burma)',
    MN: 'Mongolia',
    MO: 'Macao SAR China',
    MP: 'Northern Mariana Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NF: 'Norfolk Island',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'French Polynesia',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PM: 'St. Pierre & Miquelon',
    PN: 'Pitcairn Islands',
    PR: 'Puerto Rico',
    PS: 'Palestinian Territories',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russia',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SC: 'Seychelles',
    SD: 'Sudan',
    SE: 'Sweden',
    SG: 'Singapore',
    SH: 'St. Helena',
    SI: 'Slovenia',
    SJ: 'Svalbard & Jan Mayen',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    SS: 'South Sudan',
    ST: 'São Tomé & Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Syria',
    SZ: 'Eswatini',
    TC: 'Turks & Caicos Islands',
    TD: 'Chad',
    TF: 'French Southern Territories',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TO: 'Tonga',
    TR: 'Türkiye',
    TT: 'Trinidad & Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    UM: 'U.S. Outlying Islands',
    US: 'United States',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VA: 'Vatican City',
    VC: 'St. Vincent & Grenadines',
    VE: 'Venezuela',
    VG: 'British Virgin Islands',
    VI: 'U.S. Virgin Islands',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis & Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'South Africa',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  },
};
